# Generated by Django 4.1.5 on 2023-01-15 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('AuthorID', models.AutoField(primary_key=True, serialize=False)),
                ('AuthorName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.AutoField(primary_key=True, serialize=False)),
                ('BookTitle', models.CharField(max_length=250)),
                ('Language', models.CharField(max_length=250)),
                ('Year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book_Author',
            fields=[
                ('AuthorID', models.AutoField(primary_key=True, serialize=False)),
                ('BookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='molodkina_books.book')),
            ],
        ),
    ]
