# Generated by Django 4.1.5 on 2023-01-16 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('YearOfBirth', models.IntegerField()),
                ('YearOfDeath', models.IntegerField(blank=True, null=True)),
                ('PlaceOfBirth', models.CharField(max_length=250)),
                ('PlaceOfDeath', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Language', models.CharField(max_length=250)),
                ('YearOfPublication', models.IntegerField()),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='molodkina_books.author')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='Nationalities',
            field=models.ManyToManyField(to='molodkina_books.country'),
        ),
    ]
